<?php

function sitemap_render_menu ($menu) {
    $output = "";
    foreach ($menu as $item) {
    	$link = $item["link"];
    	if ($link["hidden"]) {
    	    continue;
    	}       
        $ff = url($link["href"]);
        if (strpos($ff, '%3Cnolink%3E') !== false) {
			$class = 'nolink_class';
			$output .= "<li><a class=".$class." href='#'" . "\">" . $link["title"] . "</a>";
        }else{
          $class ='normal_class' ; 
          $output .= "<li><a class=".$class." href=\"" . check_url(url($link["href"], $link["options"])) . "\">" . $link["title"] . "</a>";
        }
    	if ($item["below"]) {            
    	    $output .= sitemap_render_menu($item["below"]);            
    	}
        $output .= '</li>';
    }
    if($output != ''){
        $output = "<ul>".$output."</ul>";
    }    
    return $output;
}

function easy_sitemap_content() {
	
    drupal_add_css(drupal_get_path('module', 'easy_sitemap') . '/css/easy_sitemap.css');    
    $query = db_select('easy_sitemap', 'st');
    $query->fields('st', array('menu_name', 'menu_machine_name'));
    $query->condition('st.is_show', 1);
    $query->orderBy('st.sitemap_order', 'ASC');
    $result = $query->execute();
	
    foreach($result as $value) {
		$array[] = array('machine_name'=>$value->menu_machine_name,'menu_name'=>$value->menu_name);
    }

    $output = "";
    $output .= "<div id=\"easy_sitemap\">";
    if(!empty($array)) {
		foreach($array as $val) {
			$menutree_alldata = menu_tree_all_data($val['machine_name']);
			if(!empty($menutree_alldata)) {   
				$output .= sitemap_render_menu(menu_tree_all_data($val['machine_name']));
			}
		}
    }
    $output .= "</div>";
    return $output;
}


function easy_sitemap_menu() { 
    $items = array();
    $items["site-map"] = array (
	    "title" => "Easy Sitemap",
	    "page callback" => "easy_sitemap_content",
	    "access arguments" => array("access content"),
	    "type" => MENU_CALLBACK
        );
    $items['admin/config/development/easy-sitemap'] = array(
        'title' => 'Easy Sitemap Configuration',
        'page callback' => 'set_sitemap',
        'access callback' => 'easy_sitemap_access',
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}


function set_sitemap() {  
 return drupal_get_form('custom_sitemap_setting_form');
}


function custom_sitemap_setting_form($form, &$form_state) {
    $form = array();
    $form['sitemap_setting'] = array(
		'#type' => 'fieldset',        
		'#prefix' => '<table>',
		'#suffix' => '</table>',
		'#tree' => TRUE,
    );
   
    $form['sitemap_setting']['header'] = array(
		'#markup' => '<thead>
			<tr>
				<td colspan="3" align="center"><h1>Site Map Settings<h1></td>
			</tr>
			<tr>
				<th>Menu Name</th>
				<th>Show On Sitemap</th>
				<th>Site Map Order</th>
			</tr>
		</thead>',
    );

    $query = db_select('easy_sitemap', 'st');
    $query->fields('st', array('menu_name', 'menu_machine_name','is_show','sitemap_order'));
    $result = $query->execute();

    foreach ($result as $value) {        
        $data[] = $value->menu_machine_name;
    }
	
    $all_menu_list = menu_get_menus();
    $j =0;
	
    foreach ($all_menu_list as $key => $val) {
        if(!in_array($key,@$data)) {
            $query_inset = db_insert('easy_sitemap')->fields(array(
                'menu_name','menu_machine_name','is_show','sitemap_order'
                )
            );
            $query_inset->values(array(
                'menu_name' => $val,'menu_machine_name'=>$key,
                'is_show'=>0,'sitemap_order'=>0
                )
            );
            $query_inset->execute();
        }
        $opt[] = $j;
        $j++;
    }
    
   //.............................
    $que = db_select('easy_sitemap', 'st1');
    $que->fields('st1', array('menu_name', 'menu_machine_name','is_show','sitemap_order'));
    $rest = $query->execute();
    $i=0;
    foreach ($rest as $value) {
        $form['sitemap_setting'][$value->menu_machine_name] = array(
			'#prefix' => '<tr>',
			'#suffix' => '</tr>',
        );
        $form['sitemap_setting'][$value->menu_machine_name]['manu_name'] = array(
			'#markup' => $value->menu_name,
			'#prefix' => '<td>',
			'#suffix' => '</td>',
        );

        $form['sitemap_setting'][$value->menu_machine_name]['checkbox'] = array(
			'#type' => 'checkbox',
			'#options' => array(0 => "off", 1 => "on"),
			'#default_value' => $value->is_show,
			'#prefix' => '<td>',
			'#suffix' => '</td>',
        );

        $form['sitemap_setting'][$value->menu_machine_name]['select'] = array(
			'#type' => 'select',
			'#options' => $opt,
			'#default_value' => array( $value->sitemap_order ),
			'#prefix' => '<td>',
			'#suffix' => '</td>',
        );
        $i++; 
    }
    $form['submit_button'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
    );
    return $form;


}

function custom_sitemap_setting_form_submit($form, &$form_state) {
	$all_menu_list = menu_get_menus();
    foreach ($all_menu_list as $key => $value) {     
		 $check = $form_state['input']['sitemap_setting'][$key]['checkbox'];
		 $order = $form_state['input']['sitemap_setting'][$key]['select'];
		 db_update('easy_sitemap') 
		 ->fields(array('is_show' =>$check,'sitemap_order'=>$order))
		 ->condition('menu_machine_name',$key)
		 ->execute();   
    }
    drupal_set_message(t('Your configuration has been saved.'));
    drupal_goto(current_path());    

}
function easy_sitemap_access($account = NULL) {
    return user_access('administer blocks', $account) && user_access('administer menu', $account);
}

